In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
from sklearn.metrics import roc_auc_score
from pycaret import classification
from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler

warnings.filterwarnings("ignore")

In [7]:
cols = ['BertzCT', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n', 'Chi2v', 'Chi3v', 'Chi4n',
       'EState_VSA1', 'EState_VSA2', 'ExactMolWt', 'FpDensityMorgan1',
       'FpDensityMorgan2', 'FpDensityMorgan3', 'HallKierAlpha',
       'HeavyAtomMolWt', 'Kappa3', 'MaxAbsEStateIndex', 'MinEStateIndex',
       'NumHeteroatoms', 'PEOE_VSA10', 'PEOE_VSA14', 'PEOE_VSA6', 'PEOE_VSA7',
       'PEOE_VSA8', 'SMR_VSA10', 'SMR_VSA5', 'SlogP_VSA3', 'VSA_EState9',
       'fr_COO', 'fr_COO2']

# train = pd.read_csv('./train.csv')
# train.drop(['id'],axis=1,inplace=True)
train = pd.read_csv('./train.csv')
train.drop(['id','EC1','EC2'],axis=1,inplace=True)
# train.head()

# for col in cols:
#     MMscaler = MinMaxScaler()
#     train[col] = MMscaler.fit_transform(np.array(train[col]).reshape(-1,1))
    
# train

In [12]:
train['EC6'].value_counts()

0    12589
1     2249
Name: EC6, dtype: int64

In [3]:
# pred = np.array([0 for _ in range(len(test))]).astype('float')
# pred += np.array([i[1] for i in best[0].predict_proba(test)])
# pred

In [4]:
# cols.append(tar)
# classification.setup(data=train.loc[:,cols],
#                      target=tar,
#                      fold_strategy='kfold',
#                      train_size=0.8,
#                      session_id=77)
#                      # remove_outliers=True)
#                      # outliers_threshold=0.02)
#                      # outliers_method='iforest')

# best = classification.compare_models(n_select=16,fold=10,sort='AUC')
# j = 0
# k = 0
# pred = np.array([0 for _ in range(len(test))]).astype('float')
# while j < 5:
#     try:
#         pred += np.array([i[1] for i in best[j].predict_proba(test)])
#         j += 1
#         k += 1
#     except:
#         j += 1
#         pass
# pred = [i/k for i in pred]
# print(pred[:10])
# # pred = np.array([best[i].predict_proba(test) for i in range(3)]).mean(0)
# test[tar] = pred

In [ ]:
# train.drop(['id','EC1','EC2','EC4','EC5','EC6'],axis=1,inplace=True)
target = ['EC3','EC4','EC5','EC6']

test = pd.read_csv('./test.csv')
test = test.drop('id',axis=1)

for tar in tqdm(target):
    cols.append(tar)
    classification.setup(data=train.loc[:,cols],
                         target=tar,
                         fold_strategy='kfold',
                         train_size=0.8,
                         session_id=77)
                         # remove_outliers=True)
                         # outliers_threshold=0.02)
                         # outliers_method='iforest')

    best = classification.compare_models(n_select=16,fold=10,sort='AUC')
    j = 0
    k = 0
    pred = np.array([0 for _ in range(len(test))]).astype('float')
    while j < 5:
        try:
            pred += np.array([i[1] for i in best[j].predict_proba(test)])
            j += 1
            k += 1
        except:
            j += 1
            pass
    pred = [i/k for i in pred]
    print(pred[:10])
    # pred = np.array([best[i].predict_proba(test) for i in range(3)]).mean(0)
    test[tar] = pred

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/84 [00:00<?, ?it/s]

 25%|████████████████████▊                                                              | 1/4 [05:04<15:14, 304.83s/it]

[0.45626431557479236, 0.2791001388939969, 0.23444410481233105, 0.3674412674344539, 0.3471595355108674, 0.36752036634254825, 0.3710878861219006, 0.44247512375860276, 0.44465257536446645, 0.3130958046332979]

Initiated  . . . . . . . . . . . . . . . . . .                00:03:14
Status     . . . . . . . . . . . . . . . . . .        Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  K Neighbors Classifier

Processing:   0%|          | 0/84 [00:00<?, ?it/s]

In [ ]:
from pycaret import classification
tp = pd.read_csv('./train.csv')
train['EC2'] = tp['EC2']

classification.setup(data=train,
                     target='EC2',
                     fold_strategy='kfold',
                     train_size=0.8,
                     session_id=77,
                     remove_outliers=True,
                     outliers_threshold=0.02)
                     # outliers_method='iforest')
    
best = classification.compare_models(n_select=16,fold=10,sort='AUC')
# pred = np.array([best01[i].predict(test) for i in range(3)]).mean(0)
# test['EC2'] = [i[1] for i in pred]

j = 0
k = 0
pred = np.array([0 for _ in range(len(test))]).astype('float')
while j < 5:
    try:
        pred += np.array([i[1] for i in best[j].predict_proba(test)])
        j += 1
        k += 1
    except:
        j += 1
        pass
pred = [i/k for i in pred]
print(pred[:10])

test['EC2'] = pred

In [ ]:
tp = pd.read_csv('./train.csv')
train['EC1'] = tp['EC1']

classification.setup(data=train,
                     target='EC1',
                     fold_strategy='kfold',
                     train_size=0.8,
                     session_id=77,
                     remove_outliers=True,
                     outliers_threshold=0.02)
                     # outliers_method='iforest')
    
best = classification.compare_models(n_select=16,fold=10,sort='AUC')
# pred = np.array([best01[i].predict(test) for i in range(3)]).mean(0)
# test['EC2'] = [i[1] for i in pred]

j = 0
k = 0
pred = np.array([0 for _ in range(len(test))]).astype('float')
while j < 5:
    try:
        pred += np.array([i[1] for i in best[j].predict_proba(test)])
        j += 1
        k += 1
    except:
        j += 1
        pass
pred = [i/k for i in pred]
print(pred[:10])

test['EC1'] = pred

In [ ]:
# test = pd.read_csv('./test.csv').drop('id',axis=1)
# pred01 = [i[1] for i in best[0].predict_proba(test)]
# pred02 = [i[1]-0.05 for i in best01[0].predict_proba(test)]

In [ ]:
test_sub = pd.read_csv('./test.csv')

ID = test_sub['id'].values
data={'id':ID,'EC1':test['EC1'],'EC2':test['EC2']}
final_df=pd.DataFrame(data)
final_df.to_csv('submission.csv',index=False)