In [2]:
import pandas as pd
train = pd.read_csv('./train.csv')
test = pd.read_csv('./test.csv')

In [3]:
train

      Unnamed: 0        KEY_ID  YEAR MONTH  ...  VAR_52  VAR_53 VAR_54 target
0              0  532477000030  2021    11  ...   275.2  1100.4     70    0.0
1              1  532477000029  2021    11  ...   275.2  1100.0     70    0.0
2              2  532477000028  2021    11  ...   274.9  1099.6     70    0.0
3              3  532477000009  2021    11  ...   275.0  1100.0     70    0.0
4              4  532477000006  2021    11  ...   275.0  1099.6     70    0.0
...          ...           ...   ...   ...  ...     ...     ...    ...    ...
1175        1175  535621500160  2021    12  ...   270.0  1080.4     70    0.0
1176        1176  535621500158  2021    12  ...   270.0  1080.0     70    0.0
1177        1177  535621500154  2021    12  ...   270.0  1080.0     70    0.0
1178        1178  535621500162  2021    12  ...   270.1  1080.0     70    0.0
1179        1179  535621500165  2021    12  ...   270.0  1080.4     70    0.0

[1180 rows x 57 columns]

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 57 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1180 non-null   int64
 1   KEY_ID      1180 non-null   int64
 2   YEAR        1180 non-null   int64
 3   MONTH       1180 non-null   object
 4   DAY         1180 non-null   int64
 5   ID_1        1180 non-null   int64
 6   ID_2        1180 non-null   object
 7   ID_3        1180 non-null   object
 8   VAR_7       1180 non-null   int64
 9   VAR_8       1180 non-null   int64
 10  VAR_9       1180 non-null   int64
 11  VAR_10      1180 non-null   int64
 12  VAR_11      1180 non-null   int64
 13  VAR_12      1180 non-null   object
 14  VAR_13      1180 non-null   object
 15  VAR_14      1180 non-null   object
 16  VAR_15      1180 non-null   object
 17  VAR_16      1180 non-null   object
 18  VAR_17      1180 non-null   object
 19  VAR_18      1180 non-null   object
 20  VAR_19      1180 non-null   object
 21  VAR_20      1180 non-null   object
 22  VAR_21      1180 non-null   object
 23  VAR_22      1180 non-null   object
 24  VAR_23      1180 non-null   int64
 25  VAR_24      1180 non-null   object
 26  VAR_25      1180 non-null   float64
 27  VAR_26      1180 non-null   int64
 28  VAR_27      1180 non-null   float64
 29  VAR_28      1180 non-null   float64
 30  VAR_29      1180 non-null   float64
 31  VAR_30      1180 non-null   float64
 32  VAR_31      1180 non-null   float64
 33  VAR_32      1180 non-null   float64
 34  VAR_33      1180 non-null   int64
 35  VAR_34      1180 non-null   float64
 36  VAR_35      751 non-null    float64
 37  VAR_36      1180 non-null   float64
 38  VAR_37      1180 non-null   float64
 39  VAR_38      429 non-null    float64
 40  VAR_39      1180 non-null   float64
 41  VAR_40      1180 non-null   float64
 42  VAR_41      1180 non-null   float64
 43  VAR_42      751 non-null    float64
 44  VAR_43      1180 non-null   float64
 45  VAR_44      1180 non-null   float64
 46  VAR_45      1180 non-null   float64
 47  VAR_46      1180 non-null   float64
 48  VAR_47      1180 non-null   float64
 49  VAR_48      1180 non-null   float64
 50  VAR_49      429 non-null    float64
 51  VAR_50      1180 non-null   float64
 52  VAR_51      1180 non-null   float64
 53  VAR_52      1180 non-null   float64
 54  VAR_53      1180 non-null   float64
 55  VAR_54      1180 non-null   int64
 56  target      1170 non-null   float64
dtypes: float64(28), int64(14), object(15)
memory usage: 525.6+ KB