In [1]:
import random
import pandas as pd
import numpy as np
import os
import holidays

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error


import warnings
warnings.filterwarnings(action='ignore') 
korea_holidays = holidays.SouthKorea(years=2023)
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42) # Seed 고정

In [4]:
train = pd.read_csv('./train/train.csv')
test = pd.read_csv('./test/test_00.csv')
test

        시점  품목명     품종명    거래단위  등급     평년 평균가격(원)   평균가격(원)
0     T-8순  건고추      화건   30 kg  상품  537302.666667  552000.0
1     T-7순  건고추      화건   30 kg  상품  534742.000000  555743.0
2     T-6순  건고추      화건   30 kg  상품  537408.666667  559794.0
3     T-5순  건고추      화건   30 kg  상품  592768.000000  578819.0
4     T-4순  건고추      화건   30 kg  상품       0.000000  579167.0
...    ...  ...     ...     ...  ..            ...       ...
1831  T-4순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
1832  T-3순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
1833  T-2순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
1834  T-1순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
1835     T   대파  대파(일반)  10키로묶음   상       0.000000       0.0

[1836 rows x 7 columns]

In [5]:
train

             시점  품목명     품종명    거래단위  등급     평년 평균가격(원)   평균가격(원)
0      201801상순  건고추      화건   30 kg  상품  381666.666667  590000.0
1      201801중순  건고추      화건   30 kg  상품  380809.666667  590000.0
2      201801하순  건고추      화건   30 kg  상품  380000.000000  590000.0
3      201802상순  건고추      화건   30 kg  상품  380000.000000  590000.0
4      201802중순  건고추      화건   30 kg  상품  376666.666667  590000.0
...         ...  ...     ...     ...  ..            ...       ...
29371  202111중순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
29372  202111하순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
29373  202112상순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
29374  202112중순   대파  대파(일반)  10키로묶음   상       0.000000       0.0
29375  202112하순   대파  대파(일반)  10키로묶음   상       0.000000       0.0

[29376 rows x 7 columns]