In [59]:
import pandas as pd
student = pd.read_csv('./student_sentence_data.csv')
teacher = pd.read_csv('./teacher_sentence_data.csv')
trans = pd.read_csv('./student_trans.csv')

In [61]:
conf = pd.DataFrame()
conf['question'] = student['sentence']
conf['st_trans'] = trans['0']
conf['st_ans'] = student['answer']
conf['te_ans'] = teacher['answer']
conf['label'] = student['label']
# conf = conf.sample(frac=True).reset_index(drop=True)

In [105]:
conf

,question,st_trans,st_ans,te_ans,label,trans_1gram,trans_2gram,trans_3gram,trans_4gram,1gram,2gram,3gram,4gram
0,Suppose you need to measure the temperature in...,Suppose you need to measure the temperature in...,너는 농작물 밭에서 온도를 측정할 필요가 있다고 가정해라,당신이 농작물 밭에서 온도를 측정할 필요하다고 가정해보자.,1,0.995752,0.920537,0.859105,0.845154,0.630234,0.612372,0.632456,0.5
1,There are different kinds of knowledge.,There are different kinds of knowledge,지식에는 다른 종류가 있다,다른 종류의 지식이 있다.,1,1.000000,1.000000,1.000000,1.000000,0.482279,0.000000,0.000000,0.0
2,Why?,Why is it,왜일까,왜 그럴까?,1,0.795645,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,"You can be perfect, but you need to change the...","You can be perfect, but you need to change the...","너는 완벽할 수 있지만, 그것을 생각하는 방식을 변화할 필요가 있다","여러분은 완벽할 수 있다, 하지만 여러분은 그것(완벽함)에 대해 여러분이 생각하는 ...",1,1.000000,1.000000,1.000000,1.000000,0.490872,0.362692,0.000000,0.0
4,He was a violinist and composer known for his ...,He was a violinist and composer known as a uni...,그는 유니크한 퍼포먼스 방법으로 알려져있는 바이올리니스트이자 작곡가였다.,그는 그의 독특한 연주 방법으로 알려진 바이올리니스트이자 작곡가였다.,1,0.945451,0.772889,0.745356,0.612372,0.711882,0.386995,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,"Or, from the perspective of the character, Who...",Or is it because of the perspective of the cha...,또는 등장인물의 관점애서 난 ㄴㄱ?,"또는 그 등장인물의 관점에서, 나는 누구인가?",1,0.658718,0.523002,0.574294,0.577350,0.643986,0.500000,0.000000,0.0
1730,Who is this person?,His one?,얘 ㄴㄱ?,이 사람은 누구인가,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1731,If there's a single secret to storytelling the...,"If I have a secret, I believe that if I have a...",만약 이야기하기에 한가지ㅜ비밀이 있다면 난 그게ㅜ이거라 믿는다,"만약 이야기하는 일에 한 가지 비밀이 있다면, (그렇다면) 나는 그것이 이것이라고 ...",1,0.571560,0.000000,0.000000,0.000000,0.491117,0.000000,0.000000,0.0
1732,Diego,Diego,디에고,Diego,1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1733,Animals can become famous for many different r...,Animals can become famous for many reasons.,동물들은많은다양한이유들로유명해질수있다,동물들은 많은 여러 가지 이유들로 유명해질 수 있다.,1,0.937640,0.852473,0.816497,0.774597,0.000000,0.000000,0.000000,0.0

In [50]:
import soynlp
from soynlp.noun import LRNounExtractor_v2
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor
from soynlp.tokenizer import LTokenizer

import warnings
warnings.filterwarnings('ignore')

In [51]:
def corpus_init():
    f = open("./corpus_target.txt", 'w',encoding='utf8')
    f.write('')
    f.close()

def corpus_save(target):
    save = '\n'.join(target)
    f = open("./corpus_target.txt", 'a',encoding='utf8')
    f.write(save)
    f.close()

def return_tokenizer():
    corpus = DoublespaceLineCorpus("./corpus_target.txt",iter_sent=True)
    noun_extractor = LRNounExtractor_v2(verbose=True) # n_gram?
    nouns = noun_extractor.train_extract(corpus)
    scores = {word:score.score for word, score in nouns.items()}
    tokenizer = LTokenizer(scores=scores)
    return tokenizer

In [52]:
target = list(conf['te_ans'])

In [53]:
corpus_init()
corpus_save(target)

In [54]:
tokenizer = return_tokenizer()

[Noun Extractor] use default predictors
[Noun Extractor] num features: pos=3929, neg=2321, common=107
[Noun Extractor] counting eojeols
[EojeolCounter] n eojeol = 9317 from 3494 sents. mem=0.695 Gb
[Noun Extractor] complete eojeol counter -> lr graph
[Noun Extractor] has been trained. #eojeols=22421, mem=0.710 Gb
[Noun Extractor] batch prediction was completed for 3938 words
[Noun Extractor] checked compounds. discovered 109 compounds
[Noun Extractor] postprocessing detaching_features : 1587 -> 1578
[Noun Extractor] postprocessing ignore_features : 1578 -> 1544
[Noun Extractor] postprocessing ignore_NJ : 1544 -> 1539
[Noun Extractor] 1539 nouns (109 compounds) with min frequency=1
[Noun Extractor] flushing was done. mem=0.714 Gb
[Noun Extractor] 58.61 % eojeols are covered

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# trans = [i.text for i in ans]
# tfidf = TfidfVectorizer(ngram_range=(4,4)).fit(tp['corp'])
for j in range(1,5):
    tfidf = TfidfVectorizer(tokenizer=tokenizer,ngram_range=(j,j)).fit(conf['question'])
    st_vector = tfidf.transform(conf['question'])
    te_vector = tfidf.transform(conf['st_trans'])
    scores = [float(cosine_similarity(st_vector[i],te_vector[i])) for i in range(len(conf))]
    conf[f'trans_{j}gram'] = scores

In [176]:
conf[conf['trans_4gram']>0]['label'].value_counts()

1    315
0     98
Name: label, dtype: int64

In [110]:
tp = conf[conf['trans_3gram']>0]
tp[tp['label'] == 0]

,question,st_trans,st_ans,te_ans,label,trans_1gram,trans_2gram,trans_3gram,trans_4gram,1gram,2gram,3gram,4gram
712,The rest of the audience took up the suggestio...,The rest of the people also clapped together b...,나머지 사람들도 그들에 의해 함께 박수를 쳤다,나머지 청중도 그 유도에 호응하여 15분 더 그 열광에 동참했다.,0,0.252649,0.320693,0.369574,0.277350,0.191817,0.000000,0.000000,0.0
719,One answer is simplicity.,One answer is simple,하나의 답은 간단하다,한 가지 답은 단순함이다.,0,0.596275,0.809302,0.707107,0.000000,0.399212,0.000000,0.000000,0.0
722,Online bookstores welcome their customers by n...,Online bookstores that welcome customers and s...,손님들을 환영하고 새로운 책들을 제안하는 온라인 서점들,"온라인 서점은 이름으로 고객들을 환영하며, 그들이 읽고 싶어 할 수도 있는 새로운 ...",0,0.778111,0.519515,0.377964,0.277350,0.253048,0.000000,0.000000,0.0
723,Plato's allegory is a powerful metaphor for co...,Plato's fable is a powerful metaphor for consi...,플라톤의 우화는 무지와 계몽 사이의 경계를 고려하기 위한 강력한 은유이다,플라톤의 우화는 보이는 세상과 지성에 의해서 알수 있는 영역 사이이기도 한 무지와 ...,0,0.556707,0.516778,0.442619,0.324443,0.612494,0.433013,0.258199,0.0
726,Even without knowing everything about his life...,"Even if you don't know everything in his life,...",심지어 그의 삶의 모든것을 알지 못해도 셰익스피어의 팬들은 그의 기록을 자신들의 맛...,그의 일생에 대한 모든 것을 알지 못하더라도 세익스피어의 팬들은 이 페이지의 상단에...,0,0.480396,0.270125,0.095799,0.000000,0.333337,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1571,Bake in the oven for 10 to 15 minutes.,Bake in the oven,오븐에서 굽는다,10~15분 동안 오븐에서 구워라.,0,0.665983,0.555149,0.534522,0.408248,0.475104,0.000000,0.000000,0.0
1574,"For example, someone might buy the most expens...","For example, some buy the most expensive objec...",예를 들면 누구는 제일 비싼 물건을 산다. 왜냐하면 그게 제일 좋으니까.,"예를 들어, 어떤이는 가장 비싼 물품을 살지도 모른다 또는 많이 광고되는 브랜드를 ...",0,0.346338,0.305068,0.221104,0.204124,0.149961,0.000000,0.000000,0.0
1580,"On September 12, 1992, she boarded the space s...",Then she boarded the spaceship,그때 그녀는 우주선에 탑승했다,"1992년에 9월 12일, 그녀는 역사적인 8일간의 비행에 대한 과학 임무 전문가로...",0,0.282768,0.264689,0.235702,0.000000,0.261857,0.000000,0.000000,0.0
1581,Award-­winning author A. Manette Ansay was bor...,She was born and grew up,그녀는 태어낫고 자랏다,수상작가인 A. Manette Ansay는 1964년에 Michigan에서 태어났다...,0,0.418453,0.386519,0.270039,0.000000,0.000000,0.000000,0.000000,0.0
1583,Ansay went on to study and work at Cornell Uni...,"She seems to have worked in university, studie...",그녀는 대학교에서 일도 하고 공부도 하고 조교수가 된 것 같음,"Ansay는 Cornell 대학교에서 학업과 근무를 이어나갔다, 그리고 나서 Van...",0,0.466906,0.277172,0.342997,0.250000,0.370955,0.000000,0.000000,0.0

In [56]:
corpus_init()
target = list(conf['question'])
corpus_save(target)
tokenizer = return_tokenizer()

[Noun Extractor] use default predictors
[Noun Extractor] num features: pos=3929, neg=2321, common=107
[Noun Extractor] counting eojeols
[EojeolCounter] n eojeol = 5664 from 3758 sents. mem=0.709 Gb
[Noun Extractor] complete eojeol counter -> lr graph
[Noun Extractor] has been trained. #eojeols=28836, mem=0.719 Gb
[Noun Extractor] batch prediction was completed for 0 words
[Noun Extractor] checked compounds. discovered 0 compounds
[Noun Extractor] postprocessing detaching_features : 0 -> 0
[Noun Extractor] postprocessing ignore_features : 0 -> 0
[Noun Extractor] postprocessing ignore_NJ : 0 -> 0
[Noun Extractor] 0 nouns (0 compounds) with min frequency=1
[Noun Extractor] flushing was done. mem=0.724 Gb
[Noun Extractor] 0.00 % eojeols are covered

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# trans = [i.text for i in ans]
# tfidf = TfidfVectorizer(ngram_range=(4,4)).fit(tp['corp'])
for j in range(1,5):
    tfidf = TfidfVectorizer(tokenizer=tokenizer,ngram_range=(j,j)).fit(conf['te_ans'])
    st_vector = tfidf.transform(conf['te_ans'])
    te_vector = tfidf.transform(conf['st_ans'])
    scores = [float(cosine_similarity(st_vector[i],te_vector[i])) for i in range(len(conf))]
    conf[f'{j}gram'] = scores

In [58]:
conf

,question,st_trans,st_ans,te_ans,label,similar,similar_en,trans_1gram,trans_2gram,trans_3gram,trans_4gram,1gram,2gram,3gram,4gram
0,Suppose you need to measure the temperature in...,Suppose you need to measure the temperature in...,너는 농작물 밭에서 온도를 측정할 필요가 있다고 가정해라,당신이 농작물 밭에서 온도를 측정할 필요하다고 가정해보자,1,0.874919,0.999939,0.988149,0.898021,0.807831,0.790569,0.630234,0.612372,0.632456,0.5
1,There are different kinds of knowledge,There are different kinds of knowledge,지식에는 다른 종류가 있다,다른 종류의 지식이 있다,1,-0.002432,0.999995,1.000000,1.000000,1.000000,1.000000,0.482279,0.000000,0.000000,0.0
2,Why,Why is it,왜일까,왜 그럴까,1,0.362370,0.983817,0.795645,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,You can be perfect but you need to change the...,You can be perfect but you need to change the...,너는 완벽할 수 있지만 그것을 생각하는 방식을 변화할 필요가 있다,여러분은 완벽할 수 있다 하지만 여러분은 그것 완벽함 에 대해 여러분이 생각하는 ...,1,0.159095,0.999989,1.000000,1.000000,1.000000,1.000000,0.491102,0.373414,0.000000,0.0
4,He was a violinist and composer known for his ...,He was a violinist and composer known as a uni...,그는 유니크한 퍼포먼스 방법으로 알려져있는 바이올리니스트이자 작곡가였다,그는 그의 독특한 연주 방법으로 알려진 바이올리니스트이자 작곡가였다,1,0.669180,0.999886,0.940100,0.721714,0.772981,0.666667,0.711882,0.386995,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,Or from the perspective of the character Who...,Or is it because of the perspective of the cha...,또는 등장인물의 관점애서 난,또는 그 등장인물의 관점에서 나는 누구인가,1,-0.057509,0.999924,0.634081,0.490923,0.537203,0.534522,0.497998,0.000000,0.000000,0.0
1730,Who is this person,His one,얘,이 사람은 누구인가,1,0.049166,0.991457,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1731,If there s a single secret to storytelling the...,If I have a secret I believe that if I have a...,만약 이야기하기에 한가지 비밀이 있다면 난 그게 이거라 믿는다,만약 이야기하는 일에 한 가지 비밀이 있다면 그렇다면 나는 그것이 이것이라고 ...,1,0.737258,0.998686,0.560788,0.084791,0.000000,0.000000,0.533739,0.308214,0.000000,0.0
1732,Diego,Diego,디에고,,1,-0.039734,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1733,Animals can become famous for many different r...,Animals can become famous for many reasons,동물들은많은다양한이유들로유명해질수있다,동물들은 많은 여러 가지 이유들로 유명해질 수 있다,1,-0.042861,0.999932,0.937640,0.852473,0.816497,0.774597,0.000000,0.000000,0.000000,0.0

In [125]:
conf[(conf['trans_4gram']>0) & (conf['4gram']>0)]['label'].value_counts()

1    127
0     31
Name: label, dtype: int64

In [168]:
tw1,tw2,tw3,w1,w2,w3 = 0.7,0.4,0.1,0.7,0.4,0.1
tp = conf[(conf['trans_1gram'] > tw1) & (conf['trans_2gram'] > tw2) & (conf['trans_3gram'] > tw3) & (conf['1gram'] > w1) & (conf['2gram'] > w2) & (conf['3gram'] > w3)]
tp[tp['label'] == 0]

,question,st_trans,st_ans,te_ans,label,trans_1gram,trans_2gram,trans_3gram,trans_4gram,1gram,2gram,3gram,4gram
1452,Peter and Mina's grandfather meet and greet ea...,Peter and Mina's grandfather met and greeted e...,피터와 미나의 할아버지는 만나서 서로 인사를 했다.,피터와 미나의 할아버지가 만나서 서로 인사한다.,0,0.776748,0.707107,0.534522,0.408248,0.785322,0.707107,0.447214,0.0

In [62]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train,X_test,y_train,y_test = train_test_split(
    conf.loc[:,['similar','similar_en','1gram','2gram','3gram','4gram','trans_1gram','trans_2gram','trans_3gram','trans_4gram']],conf['label'],test_size=0.2,random_state=10
)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=12)
rf.fit(X_train,y_train)
pred = rf.predict(X_test)
acc = accuracy_score(pred,y_test)
print(acc)

0.7579250720461095

In [63]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
parms = {'n_estimators':list(range(100,200,10)),
         'max_depth':list(range(5,21,3))} # num of iter : using classifier
         # 'max_depth':list(range(5,11,5)),
         # 'min_samples_split':[2],
         # 'learning_rate': [0.1], # invalid ?
         # 'min_samples_leaf':[2]}
rf_clf = RandomForestClassifier(random_state=12,n_jobs=-1,verbose=True) # n_jobs ?
grid_cv = GridSearchCV(rf_clf,param_grid=parms,cv=5,n_jobs=-1,scoring='accuracy')# ,param_grid=parms
grid_cv.fit(X_train,y_train)

print(grid_cv.best_estimator_)
print(grid_cv.best_params_)
print(round(grid_cv.best_score_,4))

RandomForestClassifier(max_depth=5, n_estimators=130, n_jobs=-1,
                       random_state=12, verbose=True)
{'max_depth': 5, 'n_estimators': 130}
0.7274

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:    0.0s finished

In [64]:
pred = grid_cv.predict(X_test)
acc = accuracy_score(pred,y_test)
print(acc)

0.7579250720461095

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 130 out of 130 | elapsed:    0.0s finished

---

# Fast text

In [3]:
from gensim.models.word2vec import Word2Vec
from gensim.models.fasttext import FastText
import pandas as pd

In [17]:
def corpus_init():
    f = open("./corpus_target.txt", 'w',encoding='utf8')
    f.write('')
    f.close()

def corpus_save(target):
    save = '\n'.join(target)
    f = open("./corpus_target.txt", 'a',encoding='utf8')
    f.write(save)
    f.close()

def return_tokenizer():
    corpus = DoublespaceLineCorpus("./corpus_target.txt",iter_sent=True)
    noun_extractor = LRNounExtractor_v2(verbose=True) # n_gram?
    nouns = noun_extractor.train_extract(corpus)
    scores = {word:score.score for word, score in nouns.items()}
    tokenizer = LTokenizer(scores=scores)
    return tokenizer

In [4]:
student = pd.read_csv('./student_sentence_data.csv')
teacher = pd.read_csv('./teacher_sentence_data.csv')
trans = pd.read_csv('./student_trans.csv')

In [5]:
conf = pd.DataFrame()
conf['question'] = student['sentence'].str.replace('[^a-zA-Z]',' ')
conf['st_trans'] = trans['0'].str.replace('[^a-zA-Z]',' ')
conf['st_ans'] = student['answer'].str.replace('[^가-힣]',' ')
conf['te_ans'] = teacher['answer'].str.replace('[^가-힣]',' ')
conf['label'] = student['label']

C:\Users\User\AppData\Local\Temp\ipykernel_4276\3237010143.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  conf['question'] = student['sentence'].str.replace('[^a-zA-Z]',' ')
C:\Users\User\AppData\Local\Temp\ipykernel_4276\3237010143.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  conf['st_trans'] = trans['0'].str.replace('[^a-zA-Z]',' ')
C:\Users\User\AppData\Local\Temp\ipykernel_4276\3237010143.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  conf['st_ans'] = student['answer'].str.replace('[^가-힣]',' ')
C:\Users\User\AppData\Local\Temp\ipykernel_4276\3237010143.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  conf['te_ans'] = teacher['answer'].str.replace('[^가-힣]',' ')

In [6]:
conf

,question,st_trans,st_ans,te_ans,label
0,Suppose you need to measure the temperature in...,Suppose you need to measure the temperature in...,너는 농작물 밭에서 온도를 측정할 필요가 있다고 가정해라,당신이 농작물 밭에서 온도를 측정할 필요하다고 가정해보자,1
1,There are different kinds of knowledge,There are different kinds of knowledge,지식에는 다른 종류가 있다,다른 종류의 지식이 있다,1
2,Why,Why is it,왜일까,왜 그럴까,1
3,You can be perfect but you need to change the...,You can be perfect but you need to change the...,너는 완벽할 수 있지만 그것을 생각하는 방식을 변화할 필요가 있다,여러분은 완벽할 수 있다 하지만 여러분은 그것 완벽함 에 대해 여러분이 생각하는 ...,1
4,He was a violinist and composer known for his ...,He was a violinist and composer known as a uni...,그는 유니크한 퍼포먼스 방법으로 알려져있는 바이올리니스트이자 작곡가였다,그는 그의 독특한 연주 방법으로 알려진 바이올리니스트이자 작곡가였다,1
...,...,...,...,...,...
1729,Or from the perspective of the character Who...,Or is it because of the perspective of the cha...,또는 등장인물의 관점애서 난,또는 그 등장인물의 관점에서 나는 누구인가,1
1730,Who is this person,His one,얘,이 사람은 누구인가,1
1731,If there s a single secret to storytelling the...,If I have a secret I believe that if I have a...,만약 이야기하기에 한가지 비밀이 있다면 난 그게 이거라 믿는다,만약 이야기하는 일에 한 가지 비밀이 있다면 그렇다면 나는 그것이 이것이라고 ...,1
1732,Diego,Diego,디에고,,1
1733,Animals can become famous for many different r...,Animals can become famous for many reasons,동물들은많은다양한이유들로유명해질수있다,동물들은 많은 여러 가지 이유들로 유명해질 수 있다,1

In [18]:
corpus_init()
corpus_save(conf['te_ans'])

In [19]:
model = FastText(vector_size=20)

In [20]:
model.build_vocab(corpus_file='./corpus_target.txt')

In [21]:
model.train(
    corpus_iterable=pd.Series([i.split() for i in conf['st_ans']]),
    epochs=5,
    total_examples=model.corpus_count,
    total_words=model.corpus_total_words
)

(17124, 66380)

In [22]:
model.wv.get_vector('너무')

array([ 0.00851727, -0.01076149, -0.00447751, -0.02883685,  0.02140056,
       -0.01317486, -0.00203293,  0.02560673,  0.00874781,  0.02370157,
        0.02003126,  0.00441309,  0.01090683, -0.00287907,  0.01602023,
       -0.0047574 ,  0.03028851, -0.00193214,  0.00679519, -0.01192066],
      dtype=float32)

In [26]:
conf['similar'] = [model.wv.similarity(conf.loc[i,'st_ans'],conf.loc[i,'te_ans']) for i in range(len(conf))]

In [31]:
conf[conf['similar'] > 0.3]['label'].value_counts()

1    460
0    237
Name: label, dtype: int64

In [33]:
tp = conf[conf['similar'] > 0.3]
tp[tp['label'] == 1]

,question,st_trans,st_ans,te_ans,label,similar
0,Suppose you need to measure the temperature in...,Suppose you need to measure the temperature in...,너는 농작물 밭에서 온도를 측정할 필요가 있다고 가정해라,당신이 농작물 밭에서 온도를 측정할 필요하다고 가정해보자,1,0.874919
2,Why,Why is it,왜일까,왜 그럴까,1,0.362370
4,He was a violinist and composer known for his ...,He was a violinist and composer known as a uni...,그는 유니크한 퍼포먼스 방법으로 알려져있는 바이올리니스트이자 작곡가였다,그는 그의 독특한 연주 방법으로 알려진 바이올리니스트이자 작곡가였다,1,0.669180
5,Who can blame them,Who can blame them,누가 그들을 비난할수있나,누가 그들을 비난할 수 있겠는가,1,0.465310
6,Paleontologists focus on the history of life o...,Paleic scholars focus on the history of life o...,고생물학자들은 지구에서 생명의 역사에 집중한다,고생물학자들은 지구상에 생명체의 역사에 집중한다,1,0.538514
...,...,...,...,...,...,...
1720,You can categorize items from just one ...,You can classify products in one store,너는 하나의 가게에서 개의 상품들을 분류할 수 있다,당신은 한 가게에서만 만 개의 품목들을 범주화할 수 있다,1,0.323503
1722,Regarding climate effects in general developi...,In general according to the influence of clim...,일반적으로 기후의 영향에 따르면 개발도산국은 더 부정적인 효과를 경험할 것이다,일반적으로 기후의 영향에 관해서는 개발도상국이 더 지구 온난화의 더 부정적인 영향을...,1,0.529002
1725,Mae C Jemison was named the first black woman...,MAE C Jemison is known as the first black fem...,은 년에 첫 번째 흑인 여성 우주인으로 알려진다,은 년에 최초의 흑인 여성 우주 비행사로 임명되었다,1,0.899393
1728,For the most part the director uses natural ...,In most cases the supervision is used as a na...,대부분의 경우 감독은 자 스럽고 일반적인 종류의 카메라 위치 선정과 카메라 각도...,대부분의 경우 감독은 자연스럽고 일반적인 종류의 카메라 위치 선정과 카메라 각도들...,1,0.793102
1731,If there s a single secret to storytelling the...,If I have a secret I believe that if I have a...,만약 이야기하기에 한가지 비밀이 있다면 난 그게 이거라 믿는다,만약 이야기하는 일에 한 가지 비밀이 있다면 그렇다면 나는 그것이 이것이라고 ...,1,0.737258

In [34]:
corpus_init()
corpus_save(conf['question'])

In [35]:
model = FastText(vector_size=20) 
model.build_vocab(corpus_file='./corpus_target.txt')
model.train(
    corpus_iterable=pd.Series([i.split() for i in conf['st_trans']]),
    epochs=5,
    total_examples=model.corpus_count,
    total_words=model.corpus_total_words
)

(47195, 97830)

In [36]:
conf['similar_en'] = [model.wv.similarity(conf.loc[i,'question'],conf.loc[i,'st_trans']) for i in range(len(conf))]

In [44]:
conf

,question,st_trans,st_ans,te_ans,label,similar,similar_en
0,Suppose you need to measure the temperature in...,Suppose you need to measure the temperature in...,너는 농작물 밭에서 온도를 측정할 필요가 있다고 가정해라,당신이 농작물 밭에서 온도를 측정할 필요하다고 가정해보자,1,0.874919,0.999939
1,There are different kinds of knowledge,There are different kinds of knowledge,지식에는 다른 종류가 있다,다른 종류의 지식이 있다,1,-0.002432,0.999995
2,Why,Why is it,왜일까,왜 그럴까,1,0.362370,0.983817
3,You can be perfect but you need to change the...,You can be perfect but you need to change the...,너는 완벽할 수 있지만 그것을 생각하는 방식을 변화할 필요가 있다,여러분은 완벽할 수 있다 하지만 여러분은 그것 완벽함 에 대해 여러분이 생각하는 ...,1,0.159095,0.999989
4,He was a violinist and composer known for his ...,He was a violinist and composer known as a uni...,그는 유니크한 퍼포먼스 방법으로 알려져있는 바이올리니스트이자 작곡가였다,그는 그의 독특한 연주 방법으로 알려진 바이올리니스트이자 작곡가였다,1,0.669180,0.999886
...,...,...,...,...,...,...,...
1729,Or from the perspective of the character Who...,Or is it because of the perspective of the cha...,또는 등장인물의 관점애서 난,또는 그 등장인물의 관점에서 나는 누구인가,1,-0.057509,0.999924
1730,Who is this person,His one,얘,이 사람은 누구인가,1,0.049166,0.991457
1731,If there s a single secret to storytelling the...,If I have a secret I believe that if I have a...,만약 이야기하기에 한가지 비밀이 있다면 난 그게 이거라 믿는다,만약 이야기하는 일에 한 가지 비밀이 있다면 그렇다면 나는 그것이 이것이라고 ...,1,0.737258,0.998686
1732,Diego,Diego,디에고,,1,-0.039734,1.000000
1733,Animals can become famous for many different r...,Animals can become famous for many reasons,동물들은많은다양한이유들로유명해질수있다,동물들은 많은 여러 가지 이유들로 유명해질 수 있다,1,-0.042861,0.999932

In [43]:
conf[conf['similar_en'] > 0.999]['label'].value_counts()

1    758
0    663
Name: label, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train,X_test,y_train,y_test = train_test_split(
    conf.loc[:,['similar','similar_en']],conf['label'],test_size=0.3,random_state=10
)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=12)
rf.fit(X_train,y_train)
pred = rf.predict(X_test)
acc = accuracy_score(pred,y_test)
print(acc)

0.6410748560460653

In [ ]:
!